#!/usr/sbin/nft -f

flush ruleset

# Define variables for interfaces and LAN network
define WAN_IF = enp0s3
define LAN_IF = enp0s4
define LAN_NET = 192.168.0.0/24

table inet filter {
	chain input_lan {
		# ICMP packets from the LAN are accepted within a certain rate limit
		icmp type echo-request limit rate 5/second accept

		# DNS, DHCP, and SSH traffic for the LAN are accepted
		ip protocol . th dport vmap { tcp . 22 : accept, udp . 53 : accept, tcp . 53 : accept, udp . 67 : accept }
	}
	chain input_wan {
		# Accepts neighbor discovery protocol (NDP) traffic
		icmpv6 type { nd-neighbor-solicit, nd-router-advert, nd-neighbor-advert } accept
	}
	chain input {
		# The input hook means rules apply to traffic addressed to local systems and processes
		# Packets that do not meet the rules are dropped by policy
		type filter hook input priority filter; policy drop;

		# conntrack (ct) expressions enable stateful firewalls
		# Packets that are part of a valid established connection and related packets are accepted
		# Packets that do not follow expected connection behavior are invalid and are dropped
		ct state vmap { established : accept, related : accept, invalid : drop }

		# Incoming packets are filtered based on the input interface
		# Loopback traffic is accepted
		# Packets from the interface LAN_IF are filtered based on the rules at input_lan
        # Packets from the interface WAN_IF are filtered based on the rules at input_wan
		iifname vmap { lo : accept, $LAN_IF : jump input_lan, $WAN_IF : jump input_wan }
	}
	chain forward {
		# The forward hook means rules apply to traffic that are not addressed to local systems and processes
		# Packets that do not meet the rules are dropped by policy
		type filter hook forward priority filter; policy drop;

		ct state vmap { established  : accept, related : accept, invalid : drop }

		# Packets from the interface LAN_IF (input interface name) to the internet or other internal systems are accepted
		iifname $LAN_IF accept
	}
	chain output {
		type filter hook output priority filter; policy accept;
	}
}

table ip nat {
	chain prerouting {
		type nat hook prerouting priority -100; policy accept;
	}
	chain postrouting {
		type nat hook postrouting priority 100; policy accept;
		# Masquerade LAN IP to public IP
		ip saddr $LAN_NET oifname $WAN_IF masquerade
	}
}